name: Run all test specs

on:
    # schedule:
    #   - cron: '* 5 * * *'
    #   - cron: '* 20 * * *'
    workflow_dispatch:

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: npm ci
            - name: Install Playwright Browsers - Chromium, Firefox, Webkit
              run: npx playwright install --with-deps chromium webkit firefox
            - name: Run Playwright tests
              run: npx playwright test
            - name: Upload Playwright HTML Report as artifact
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: playwright-html-report
                  path: playwright-report/
